### ISSUE TITLE
Remove auth.ini

### ISSUE THREAD

**Issue by KawaiiGator** [jcsumlin/call-all-plugin#1]
If you ever put real credentials into auth.ini and git is tracking it, that's like a loaded weapon. Thousands of people have uploaded passwords to Github because they weren't paying attention to their commits. I would recommend that you remove the file from the git index and add it to .gitignore:

```
git rm --cached auth.ini
echo auth.ini >> .gitignore
```

If you want to safely track a template, you can create auth.ini.sample. A popular alternative is using environmental variables, but that's also more complicated.

**Comment by jcsumlin** [comment]
Done and done! Thanks for your support!
